Kgp 96 backend dodac testy integracyjne do kontrolerow cleanup
KGP2/KGP.TicketApp pull request #18
Opened 2023-04-29 17:56 UTC by mwdowski

2023-04-30 19:28 UTC, nobster14 requested changes
Autoryzacja działa, ale teraz jakiś wyjątek w sqlu rzuca, więc musisz zerknąć

2023-05-01 14:52 UTC, nobster14 requested changes

2023-05-01 14:52 UTC, nobster14 commented on KGP.TicketApp.Tests.Integration/Backend/Controllers/EventController/GetEventsTests.cs
W BaseControllerTest zrobiłbym tworzenie każdego przykładowe obiektu(lokacja, client itd. bo sie powtarza), a pozniej dla kazdego kontrolera funkcje inicjujacą, bo tez sie powtarza. Czyli zrobilbym klase BaseControllerTest(tutaj inicjacja i definicja przykładoweh obiektów) -> EventControllerTests(tutaj definicja addinitialdata) -> Get/PostEventTests

2023-05-05 18:10 UTC, mwdowski commented on KGP.TicketApp.Tests.Integration/Backend/Controllers/EventController/GetEventsTests.cs
imo to zły pomysł. Imo przez to, że byśmy ukrywali w klasach testujących zawartość danych, tracimy na przejrzystości

2023-05-05 21:08 UTC, nobster14 commented on KGP.TicketApp.Tests.Integration/Backend/Controllers/EventController/GetEventsTests.cs
to akceptuje, w sumie w testach przejrzystosc > powtarzanie

2023-05-05 21:08 UTC, nobster14 approved these changes

2023-05-05 21:09 UTC, merged